### ISSUE TITLE
RMarkdown and html question

### ISSUE THREAD

**Issue by jacobtnyoung** [DS4PS/cpp-526-fall-2020#20]
I have a question about how to do something in an .Rmd document. I want to have the html render text that references a particular value in the R code. For example:

```
{r}
dim(dat)

As you can see, the file has `dim(dat)[1]` rows...

```
So, I would the text to read "As you can see, the file has 27 rows". So, I would want the actual text to reflect the value returned by R in the console. Not the code itself (as I have wrote it). Make sense?

Thanks!

**Comment by lecy** [comment]
I think the problem would be that you need to run a chunk before the object exists. I know you can reference universal objects like the date and time in RMD titles, but not sure how you would reference a data value. 

You can always omit the YAML title and add another title with the HTML <h1> tag. You could hide a chunk before that to create the object you need. Would that work?  

Otherwise not sure.

**Comment by jamisoncrawford** [comment]
So this is really cool and something I did not know!

According to this [section of the R Markdown Cookbook](https://bookdown.org/yihui/rmarkdown-cookbook/dynamic-yaml.html), you can create the YAML header without including `title:` and, after you've created an object in a latter code chunk, you can append it to the YAML header with the following syntax:

```
---
title: "Words `r object` more words"
---
```

Try running the following in a .Rmd file (this and nothing else):

````
---
author: "RStudio"
date: "9/20/2020"
output: html_document
---

```{r include = FALSE}

knitr::opts_chunk$set(echo = TRUE)

```

## Header

Some text...

```{r}

avg <- round(x = mean(mtcars$mpg), 
             digits = 2)

```

---
title: "Cars Averaging `r avg` MPG"
---

````

This creates:

![image](https://user-images.githubusercontent.com/15643196/93721291-0dc89180-fb5d-11ea-96c4-f4a7e99747e5.png)

Awesome!

**Comment by lecy** [comment]
![](https://media.tenor.com/images/c03871be254b962313ed474b1b5c7872/tenor.gif)

**Comment by jacobtnyoung** [comment]
Ok nice!

I was just looking to have it build into the text. But, you can do that by just removing the title section:

```
---
author: "RStudio"
date: "9/20/2020"
output: html_document
---

```{r include = FALSE}

knitr::opts_chunk$set(echo = TRUE)

```

## Header

Some text...

```{r}

avg <- round(x = mean(mtcars$mpg), 
             digits = 2)

```

I don't want to have to replace the value here, so the MPG is `r avg`.
```

**Comment by jacobtnyoung** [comment]
Thanks for the help!

**Comment by jamisoncrawford** [comment]
@jacobtnyoung you bet! Thanks for asking about it!
