### ISSUE TITLE
Problem with date variable

### ISSUE THREAD

**Issue by jacobtnyoung** [DS4PS/cpp-526-fall-2020#23]
Hi all,

I a working with a file for my code through project and can't for the life of my figure out an error I am getting. Specifically, you can get the file here:

```
url <- "https://www.phoenixopendata.com/dataset/cc08aace-9ca9-467f-b6c1-f0879ab1a358/resource/0ce3411a-2fc6-4302-a33f-167f68608a20/download/crimestat.csv"
crime.data <- read.csv(url, as.is = TRUE, header = TRUE)
```

The error I am getting is that the `strptime()` function is returning values of NA. For example:

```
head( crime.data$OCCURRED.ON )
date.vec <- strptime( crime.data$OCCURRED.ON, format="%m/%d/%y %H:%M" )
head( date.vec )
```
returns NA for the dates and times. The format looks to be the same as the data as discussed on the [Lab 5 section discussing dates/times](https://ds4ps.org/cpp-526-sum-2020/labs/lab-05-instructions.html). So, I am not sure what the issue is.

Any help?

**Comment by lecy** [comment]
I'm looking at the file and I see some empty values for that field: 

![image](https://user-images.githubusercontent.com/1209099/94615486-b6ad7580-025c-11eb-811b-8e0a0a6c1213.png)

It might just be a matter of dropping empty cases first? 

```
filter( dat, ! is.na(x) )
```

**Comment by jacobtnyoung** [comment]
I tried that and still get the same values reported.

**Comment by jamisoncrawford** [comment]
@jacobtnyoung give it a try with Tidyverse package `lubridate`.

```
url <- paste0("https://www.phoenixopendata.com/dataset/cc08aace",
              "-9ca9-467f-b6c1-f0879ab1a358/resource/0ce3411a-2",
              "fc6-4302-a33f-167f68608a20/download/crimestat.csv")

crime.data <- read.csv(url, 
                       as.is = TRUE, 
                       header = TRUE)

library(lubridate)

date.vec <- mdy_hm(crime.data$OCCURRED.ON)

head(date.vec)
```

Should do the trick!

**Comment by jacobtnyoung** [comment]
Thanks! Yes, I had done using lubridate and things worked fine. I was just trying to use the strptime function. But, it looks like I will stick with lubridate! Thank you!

**Comment by jamisoncrawford** [comment]
Sure thing!  Love lubridate!

**Comment by lecy** [comment]
Got it, I misunderstood the question. 

You had specified the wrong formatting. **format="%m/%d/%y** is for 11/01/15 type dates. You need a capital Y when they include the full four-digit year format:

```r
> head( crime.data$OCCURRED.ON )
[1] "11/01/2015  00:00" "11/01/2015  00:00" "11/01/2015  00:00"
[4] "11/01/2015  00:00" "11/01/2015  00:00" "11/01/2015  00:00"
> date.vec <- strptime( crime.data$OCCURRED.ON, format="%m/%d/%Y %H:%M" )
> head( date.vec )
[1] "2015-11-01 MST" "2015-11-01 MST" "2015-11-01 MST" "2015-11-01 MST"
[5] "2015-11-01 MST" "2015-11-01 MST"
```

In practice I would definitely recommend lubridate. The strptime function is pretty pedantic, but interesting to see how dates work.

You will still have NAs from the blank dates. But that wasn't the main issue. 

```r
> sum( is.na( date.vec ) )
[1] 420
```

**Comment by jacobtnyoung** [comment]
Boom! Thanks Jesse! So, %y is for "/15" and %Y is for "/2015"?

**Comment by jacobtnyoung** [comment]
Oh ok. I see that now in the description on the Lab 5 page. Thanks!
