### ISSUE TITLE
Geocoded data

### ISSUE THREAD

**Issue by jacobtnyoung** [DS4PS/cpp-526-fall-2020#24]
Hi all,

I was looking to get lat/long coordinates for some data I am working with for the code through. I noticed that `ggmap` uses googles API to pull coordinates from addresses. But, there is a limit on the requests you can make per day. Did anyone come across an API where you can pass block level addresses (e.g. 13XX Holly St) and create the coordinates? Thanks!

**Comment by lecy** [comment]
You might try the Census geocoding tool. It is free. 

See step 03 here: 

https://nonprofit-open-data-collective.github.io/open-1023-ez-dataset/

I'm not sure how it will handle block-level addresses, though. You might replace X's with 0's before sending a request?

**Comment by jamisoncrawford** [comment]
Hi @jacobtnyoung - have you tried using the Census Geocoder?

It limits queries to up to 10,000 addresses at a time but there's no limit to how many times you can batch geocode addresses:

https://geocoding.geo.census.gov/geocoder/geographies/addressbatch?form

Just make sure you use the sample spreadsheet provided to make sure your data are in the same format and order.  There are some addresses that won't get picked up (usually apartments and that sort of thing) but you can manually select a nearby address - usually does the trick if it's not overwhelming!

**Comment by jamisoncrawford** [comment]
Aaaaand @lecy beat me to it!

**Comment by jacobtnyoung** [comment]
That will work (I think!). Thanks!
