### ISSUE TITLE
Data changing between .rmd and .html file

### ISSUE THREAD

**Issue by ekmcintyre** [DS4PS/cpp-526-fall-2020#5]
I finished Lab 01 and knitted the .html file. However, when I reviewed my answers, all of the solutions to the codes had changed. For Question 1, my answer in the .rmd script is a significantly smaller number than the answer that appeared in the .html file. All of my other numbers are off as well. I also noticed that when finding the amount of parcels and vacant lots in each neighborhood for questions 5 and 6, my .rmd script is missing a few of the neighborhoods that are showing up in the .html file. How do I fix this?

**Comment by lecy** [comment]
Try re-running the chunks in your RMD file starting from the place where you load the data. 

Just guessing here from your description (I would have to see the RMD to confirm), but you likely altered your data in your RMD file through inter-active coding, then did not include those steps in the final file. 

The answers embedded in your RMD file represent the results from the last time you ran a chunk. 

The knitted HTML version will start at the top and run chunks sequentially (not always the case when you are in interactive mode). The HTML version will likely be correct. Your RMD version probably has a "ghost in the machine". 

Reload your data and run the chunks in order, I bet the answers converge.

**Comment by lecy** [comment]
It's similar to the problem: 

```
( 6 + 4 ) / 2  does NOT equal 6 + 4 / 2
```

**Comment by ekmcintyre** [comment]
I downloaded the template again and started over. This time I ran all the codes correctly from the start and the results in the .rmd and .html files matched. Thanks for the tip!
